# Використовуємо версію 3.8 для сумісності
version: '3.8'

services:
  # Основний сервіс API з Flask (ПЗ)
  app:
    build: .
    # Критично: Прокидаємо порт для зовнішнього доступу (для тестів у CI/CD)
    ports:
      - "5000:5000"
    # Критично: Явно вказуємо ім'я контейнера, щоб PyTest його знайшов
    container_name: app-api
    hostname: app-api # Допомагає у мережі Docker
    
    # Залежність: запускати тільки після az_simulator
    depends_on:
      - az_simulator
    networks:
      - app_network

  # Сервіс-заглушка для апаратної зони (АЗ)
  az_simulator:
    image: nginx:alpine
    container_name: az-simulator
    hostname: hw-simulator
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"]

# Створюємо спільну мережу для зв'язку між контейнерами
networks:
  app_network:
    driver: bridge
